### ISSUE TITLE
Error en: python setup install

### ISSUE THREAD

**Issue by cdiazbas** [aasensio/pyiacsun#1]
##### Problema al compilar:

gcc -fno-strict-aliasing -I/Users/cdiazbas/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/cdiazbas/anaconda/include/python2.7 -c pyiacsun/radtran/sourceMilne/pymilne.c -o build/temp.macosx-10.5-x86_64-2.7/pyiacsun/radtran/sourceMilne/pymilne.o
pyiacsun/radtran/sourceMilne/pymilne.c:242:10: fatal error: 'numpy/arrayobject.h' 
file not found
# include "numpy/arrayobject.h"

```
     ^
```

1 error generated.
error: command 'gcc' failed with exit status 1

**Comment by aasensio** [comment]
He modificado ligeramente el setup.py para ver si se arregla. En cualquier caso, si tienes un directorio build por ahí, bórralo. A veces da problemas.

**Comment by cdiazbas** [comment]
He borrado el "build", he actualizado a la última versión y todo va perfecto!
Compilado en mac OS 10.11
